# Google App Engine configuration for Streamlit app
runtime: python39
entrypoint: streamlit run web_app.py --server.port $PORT --server.address 0.0.0.0

instance_class: F2

env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_PORT: "8080"
  DATA_BACKEND: "sql"
  DB_NAME: "EveCalcDB"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"
  CLOUD_SQL_CONNECTION_NAME: "${CLOUD_SQL_CONNECTION_NAME}"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
- url: /.*
  secure: always
  script: auto

# Resources configuration
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
