app = "eve-echoes-optimizer-pl"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  STREAMLIT_SERVER_PORT = "8080"
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
  DATA_ROOT = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = 2048

