app = "eve-echoes-optimizer"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  STREAMLIT_SERVER_PORT = "8080"
  STREAMLIT_SERVER_HEADLESS = "true"
  DATA_ROOT = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/_stcore/health"

[[vm]]
  size = "shared-cpu-1x"

