app = "eve-echoes-optimizer-pl"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  STREAMLIT_SERVER_PORT = "8080"
  STREAMLIT_SERVER_HEADLESS = "true"
  DATA_ROOT = "/data"

[http_service]
  internal_port = 8080
  force_https = true

